server:
  port: 5050
spring:
  datasource:
    driver-class: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
    
  jpa:
    hibernate:
      ddl-auto: update
      
plan-api:
 messages:
  planSaveSucc: Plan Saved Successfully
  planSaveFail: Plan Save Failed
  planUpdateSucc: Plan Updated Successfully
  planUpdateFail: Plan Update Failed
  planDeleteSucc: Plan Deleted Successfully
  planDeleteFail: Plan Delete Failed
  planStatusChange: Plan Status Changed Successfully
  planStatusChangefail: Plan Status change Failed
  
  
